# Generated by Django 2.0 on 2017-12-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=64, verbose_name='日期')),
                ('code', models.CharField(max_length=64, verbose_name='代码')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('present_price', models.CharField(max_length=64, null=True, verbose_name='现价')),
                ('range', models.CharField(max_length=64, null=True, verbose_name='涨跌幅')),
                ('price_range', models.CharField(max_length=64, null=True, verbose_name='涨跌')),
                ('rise_speed', models.CharField(max_length=64, null=True, verbose_name='涨速')),
                ('change_hands', models.CharField(max_length=64, null=True, verbose_name='换手')),
                ('volume_ratio', models.CharField(max_length=64, null=True, verbose_name='量比')),
                ('amplitude', models.CharField(max_length=64, null=True, verbose_name='振幅')),
                ('turnover', models.CharField(max_length=64, null=True, verbose_name='成交额')),
                ('floating_stock', models.CharField(max_length=64, null=True, verbose_name='流通股')),
                ('circulation_market_value', models.CharField(max_length=64, null=True, verbose_name='流通市值')),
                ('pe_ratio', models.CharField(max_length=64, null=True, verbose_name='市盈率')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '基本信息',
                'verbose_name_plural': '基本信息',
            },
        ),
    ]
